## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)

library(ggsci)
library(tidyverse)
library(survival)
library(splines)
library(Greg)
library(timereg)
library(multcomp)
library(riskRegression)
library(prodlim)
library(viridis)
library(table.glue)
library(flextable)
library(survminer)
library(cmprsk)
library(officer)
library(cowplot)

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("border", "flextable")
conflict_prefer("font", "flextable")
conflict_prefer("rotate", "flextable")
conflict_prefer("get_legend", "cowplot")


library(rmarkdown)
